/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author NadiaRezaSavira
 */
public class Pengembalian extends javax.swing.JFrame {

    /**
     * Creates new form Pengembalian
     */
    public Home Home;
    public Login Login;
    public Connection kon;
    public Statement stmt;
    public PreparedStatement pps;
    public ResultSet rslt;
    private DefaultTableModel deta;
    
    Koneksi konek;
    
    public void tambah() {
        txtNotrans.setText("");
        //cbNopinjam.setText("");
        //jdTglKembali.setText("");
        //cbStatus.setText("");
    }
    
    public Pengembalian() {
        initComponents();
        konek = new Koneksi();
        setTitle("Data Pengembalian Buku");
        setLocationRelativeTo(null);
        tampil();
        combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnYatidak = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nopinjam = new javax.swing.JLabel();
        tglkembali = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbKembali = new javax.swing.JTable();
        notrans = new javax.swing.JLabel();
        txtNotrans = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jdTglkembali = new com.toedter.calendar.JDateChooser();
        cbStatus = new javax.swing.JComboBox();
        cbNopinjam = new javax.swing.JComboBox();
        txtDenda = new javax.swing.JLabel();
        jrYa = new javax.swing.JRadioButton();
        jrTidak = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnKembali = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel2.setFont(new java.awt.Font("Hot Mustard BTN", 0, 18)); // NOI18N
        jLabel2.setText("daftar pengembalian buku");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/minilogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("VAGRounded BT", 0, 14)); // NOI18N
        jLabel4.setText("Form");

        nopinjam.setText("No Pinjam:");

        tglkembali.setText("Tanggal Kembali:");

        status.setText("Status:");

        btnTambah.setText("Tambahkan");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel9.setText("© copyright Nadya Hadiyanti (4513210027)");

        TbKembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Np Pinjam", "Tgl Kembali", "Status", "Denda"
            }
        ));
        TbKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbKembaliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbKembali);

        jScrollPane2.setViewportView(jScrollPane1);

        notrans.setText("No Transaksi:");

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jdTglkembali.setMaxSelectableDate(new java.util.Date(253370743293000L));
        jdTglkembali.setMinSelectableDate(new java.util.Date(-62135791107000L));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Status", "Tepat", "Telat" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        cbNopinjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No pinjam" }));
        cbNopinjam.setToolTipText("");

        txtDenda.setText("Denda:");

        btnYatidak.add(jrYa);
        jrYa.setText("Ya");

        btnYatidak.add(jrTidak);
        jrTidak.setText("Tidak");

        jMenu1.setText("Menu");

        mnKembali.setText("Kembali");
        mnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKembaliActionPerformed(evt);
            }
        });
        jMenu1.add(mnKembali);

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nopinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tglkembali, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(notrans, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNotrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbNopinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jdTglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrYa)
                        .addGap(18, 18, 18)
                        .addComponent(jrTidak)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbNopinjam, cbStatus, jdTglkembali, txtNotrans});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCari, btnTambah, btnhapus});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nopinjam, notrans, status, tglkembali, txtDenda});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notrans)
                            .addComponent(txtNotrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nopinjam)
                                    .addComponent(cbNopinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(tglkembali))
                            .addComponent(btnhapus)))
                    .addComponent(jdTglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDenda)
                    .addComponent(jrYa)
                    .addComponent(jrTidak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbNopinjam, cbStatus, jdTglkembali, txtNotrans});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nopinjam, notrans, status, tglkembali, txtDenda});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKembaliActionPerformed
        try {
            Home = new Home();
            Home.setVisible(true);
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mnKembaliActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        try {
            Login = new Login();
            Login.setVisible(true);
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            Connection kon = konek.getKoneksi();
            Date tanggal = new Date();
            SimpleDateFormat formatTk = new SimpleDateFormat("dd MMMM yyyy");
            String k = formatTk.format(jdTglkembali.getDate());
            String radioBtn = "";
            
            if (cbNopinjam.getSelectedItem().toString().equals("")) {
                JOptionPane.showMessageDialog(null, "No Pinjam tidak boleh kosong");
            } else if (jdTglkembali.getDate().equals("")) {
                JOptionPane.showMessageDialog(null, "Tanggal kembali tidak boleh kosong");
            } else if (cbStatus.getSelectedItem().toString().equals("")) {
                JOptionPane.showMessageDialog(null, "Status tidak boleh kosong");
            } else if ((jrYa.getAccessibleContext().equals("")) && (jrTidak.getAccessibleContext().equals(""))) {
                JOptionPane.showMessageDialog(null, "Keterangan Denda tidak boleh kosong");
            } else {
                if (jrYa.isSelected()) {
                    radioBtn = jrYa.getText();
                } else {
                    radioBtn = jrTidak.getText();
                }
                
                //String kode = "select * from where no_transaksi = '"+txtNotrans.getText();
                String sql = "insert into pengembalian values('"+cbNopinjam.getSelectedItem().toString()+"','"+k+"','"
                        +cbStatus.getSelectedItem().toString()+"','"+radioBtn+"')";
                stmt = kon.createStatement();
                stmt.executeUpdate(sql);
            
                    JOptionPane.showMessageDialog(null, "Data Berhasil Tersimpan");
                    //txtNotrans.setText("");
                    cbNopinjam.setSelectedIndex(0);
                    jdTglkembali.setDate(tanggal);
                    cbStatus.setSelectedIndex(0);
                    btnYatidak.setSelected(null, rootPaneCheckingEnabled);
            }
            tampil();           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda ingin menghapus data ini?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            try {
                Connection kon = konek.getKoneksi();
                String sql = "delete from pengembalian where no_transaksi = '"+txtNotrans.getText()+"'";
                Statement stmt = kon.createStatement();
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                txtNotrans.setText("");
                tampil();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void TbKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbKembaliMouseClicked
        int a = TbKembali.getSelectedRow();
            if (a >= 0) {
                txtNotrans.setText(deta.getValueAt(a, 0).toString());
                txtNotrans.setEditable(false);
                cbNopinjam.setSelectedItem(deta.getValueAt(a, 1).toString());
                cbNopinjam.setEditable(false);
                //jdTglkembali.setDate(deta.getValueAt(a, 2).toString());
                //jdTglkembali.setEditable(false);
                cbStatus.setSelectedItem(deta.getValueAt(a, 3).toString());
                cbStatus.setEditable(false);
                //btnYatidak.setSelected(null, rootPaneCheckingEnabled);
                //btnYatidak.setEditable(false);
            }
    }//GEN-LAST:event_TbKembaliMouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try{
            Connection kon = konek.getKoneksi();
            String sql = "Select * from pengembalian where no_transaksi='" +txtCari.getText()+ "'";
            ResultSet rslt = stmt.executeQuery(sql);
            if (rslt.next()) {
                txtNotrans.setText(rslt.getString("no_transaksi"));
                }
            }
        catch (Exception e){
            //TbPinjam.setModel(deta);

        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void combo(){
        try {
            Connection kon = konek.getKoneksi();
            Statement stmt = kon.createStatement();
            String sql = "select * from pinjam";
            ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                cbNopinjam.addItem(rslt.getString("no_pinjam"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Terjadi Kesalahan" +e);
        }
    }
    
    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        try {
            Connection kon = konek.getKoneksi();
            Statement stmt = kon.createStatement();
            String sql = "select * from pinjam";
            ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                cbNopinjam.addItem(rslt.getString("no_pinjam"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Terjadi Kesalahan" +e);
        }
    }//GEN-LAST:event_cbStatusActionPerformed

    private void tampil(){
        try {
        Object [] row =  {"No Transaksi","No Pinjam", "Tgl Kembali", "Status", "Denda"};
        deta = new DefaultTableModel(null, row);
        TbKembali.setModel(deta);
        TbKembali.setBorder(null);
        jScrollPane2.setViewportView(TbKembali);
        String notrans="",nopinjam="",tglkembali="",status="",denda="";
        try {
            Connection kon = konek.getKoneksi();
            String sql = "select * from pengembalian";
            stmt = kon.createStatement();
            ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                notrans = rslt.getString("no_transaksi");
                nopinjam = rslt.getString("no_pinjam");
                tglkembali = rslt.getString("tgl_kembali");
                status = rslt.getString("status");
                denda = rslt.getString("denda");
                
                String [] muncul = {notrans,nopinjam,tglkembali,status,denda};
                deta.addRow(muncul);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Query salah");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbKembali;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup btnYatidak;
    private javax.swing.JButton btnhapus;
    private javax.swing.JComboBox cbNopinjam;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdTglkembali;
    private javax.swing.JRadioButton jrTidak;
    private javax.swing.JRadioButton jrYa;
    private javax.swing.JMenuItem mnKembali;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JLabel nopinjam;
    private javax.swing.JLabel notrans;
    private javax.swing.JLabel status;
    private javax.swing.JLabel tglkembali;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel txtDenda;
    private javax.swing.JTextField txtNotrans;
    // End of variables declaration//GEN-END:variables
}
